### ISSUE TITLE
Multiple conversation threads

### ISSUE THREAD

**Issue by tw9mini** [ading2210/poe-api#34]
I'm trying to wrap my head about this.
Basically, I'd like to have multiple independent conversations without chat breaks with one bot.
It's probably not possible, I would need multiple tokens to do so, right?

**Comment by ading2210** [comment]
Theoretically, this has become possible recently with the addition of custom bots. It should be possible to create a new bot for each conversation, and just delete it once the conversation is over. Currently though, I'm on vacation so I have no way to work on this.

**Comment by tw9mini** [comment]
That's a brilliant idea, however, enjoy your vacation for now, thanks :)

**Comment by xoiga123** [comment]
Is the rate limit shared between different bots? Creating 10 bots but only chatting to each once a minute is sad. I'm currently using multiple tokens with threading, seems good

**Comment by Yarkis01** [comment]
> Is the rate limit shared between different bots? Creating 10 bots but only chatting to each once a minute is sad. I'm currently using multiple tokens with threading, seems good

I made some tests on my side, and for the "free" bots, there is a limitation of messages per minutes and which is fixed at 10 messages per minutes.
Unfortunately, this limit is common with all bots (even custom bots)
![Results of my tests](https://i.imgur.com/OmSi7cx.png)

**Comment by maxcurrent420** [comment]
Yeah probably shouldn't abuse it before we get better local models going. I made a script to have them bounce messages from one bot to another, and have a conversation. Was trying to get it so that I could have three in the same conversation but I had trouble as it would send the response from the second bot to both itself and the third and things like that. But it's good for getting them to keep each other on task and discussing a topic.

**Comment by ading2210** [comment]
This has been possible for a while with the custom bot functionality.
