### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by User1231300** [ading2210/poe-api#7]
I just found the repo. Well done! i'm currently playing with it. Do you know what the daily limits are?

**Comment by ading2210** [comment]
For GPT-4 and Claude+, they limit free users to 1 message per day, but on all of the other models, there doesn't seem to be a rate limit.

**Comment by User1231300** [comment]
Hey, thank you for your kind answer. Did you also experiment with the message lenght limit? I can't seem to find an definitive answer.

**Comment by ading2210** [comment]
I've never tried to test for a length limit, but since they're likely just using the OpenAI APIs, the limit is likely 4096 tokens, according to the [OpenAI API documentation](https://platform.openai.com/docs/models/gpt-3-5). For Claude, I'm not sure about the length limit, but it should be similar to the OpenAI models.
